package vista;

import conexion.Conexion;
import controlador.Ctrl_Admin;
import controlador.Ctrl_Cliente;
import controlador.Ctrl_Persona;

import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Administrador;
import modelo.Cliente;
import modelo.Direccion;
import modelo.Persona;
import modelo.Usuario;

/**
 *
 * @author ediso
 */
public class InterEditarAdministrador extends javax.swing.JInternalFrame {

    private int idUsuario = 0;
    private Administrador admin;
    private Administrador adminAux;

    public InterEditarAdministrador(Administrador admin) {
        initComponents();
        //this.setSize(new Dimension(700, 650));
        this.setTitle("Cuenta");

        this.admin = admin;
        adminAux = admin;
        ColocarInfo(admin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_apellido1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_apellido2 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Jdate_Nacimiento = new com.toedter.calendar.JDateChooser();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_Curp = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel = new javax.swing.JLabel();
        cBox_estado = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_localidad = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_CP = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_Calle = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_num = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txt_password1 = new javax.swing.JPasswordField();
        jPanel15 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txt_password2 = new javax.swing.JPasswordField();
        jButton_Guardar = new javax.swing.JButton();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jPanel3.setLayout(new java.awt.GridLayout(13, 1));

        jPanel2.setMinimumSize(new java.awt.Dimension(160, 100));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(160, 100));
        jPanel2.setLayout(new java.awt.GridLayout(2, 0, 20, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setLabelFor(txt_Nombre);
        jLabel2.setText("Nombre:");
        jLabel2.setToolTipText("");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jLabel2.setMaximumSize(new java.awt.Dimension(61, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(61, 30));
        jLabel2.setPreferredSize(new java.awt.Dimension(61, 30));
        jPanel2.add(jLabel2);

        txt_Nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_Nombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_Nombre.setDragEnabled(true);
        txt_Nombre.setMinimumSize(new java.awt.Dimension(64, 30));
        txt_Nombre.setPreferredSize(new java.awt.Dimension(160, 30));
        jPanel2.add(txt_Nombre);

        jPanel3.add(jPanel2);

        jPanel4.setLayout(new java.awt.GridLayout(2, 0, 20, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Apellido Paterno:");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanel4.add(jLabel3);

        txt_apellido1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_apellido1.setMinimumSize(new java.awt.Dimension(160, 24));
        txt_apellido1.setPreferredSize(new java.awt.Dimension(160, 24));
        jPanel4.add(txt_apellido1);

        jPanel3.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(2, 0, 20, 0));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Apellido Materno:");
        jLabel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanel5.add(jLabel9);

        txt_apellido2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel5.add(txt_apellido2);

        jPanel3.add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout(2, 0, 20, 0));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Fecha de nacimiento:");
        jLabel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanel6.add(jLabel7);
        jPanel6.add(Jdate_Nacimiento);

        jPanel3.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(2, 0, 20, 0));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Curp:");
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanel7.add(jLabel4);

        txt_Curp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel7.add(txt_Curp);

        jPanel3.add(jPanel7);

        jPanel8.setLayout(new java.awt.GridLayout(2, 0, 20, 0));

        jLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel.setText("Estado:");
        jLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanel8.add(jLabel);

        cBox_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aguascalientes", "Baja California ", "Baja California Sur", "Campeche ", "Chiapas", "Chihuahua ", "Ciudad de México ", "Coahuila ", "Colima ", "Durango ", "Estado de México ", "Guanajuato ", "Guerrero ", "Hidalgo", "Jalisco ", "Michoacán ", "Morelos ", "Nayarit ", "Nuevo León ", "Oaxaca ", "Puebla", "Querétaro ", "Quintana Roo ", "San Luis Potosí ", "Sinaloa ", "Sonora ", "Tabasco ", "Tamaulipas ", "Tlaxcala ", "Veracruz ", "Yucatán ", "Zacatecas " }));
        jPanel8.add(cBox_estado);

        jPanel3.add(jPanel8);

        jPanel9.setLayout(new java.awt.GridLayout(2, 0, 20, 0));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Localidad:");
        jLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanel9.add(jLabel5);

        txt_localidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel9.add(txt_localidad);

        jPanel3.add(jPanel9);

        jPanel10.setLayout(new java.awt.GridLayout(2, 0, 20, 0));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Codigo postal:");
        jLabel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanel10.add(jLabel6);

        txt_CP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel10.add(txt_CP);

        jPanel3.add(jPanel10);

        jPanel11.setLayout(new java.awt.GridLayout(2, 0, 20, 0));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Calle:");
        jLabel8.setAlignmentX(1.0F);
        jLabel8.setAlignmentY(10.0F);
        jLabel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanel11.add(jLabel8);

        txt_Calle.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel11.add(txt_Calle);

        jPanel3.add(jPanel11);

        jPanel12.setLayout(new java.awt.GridLayout(2, 0, 20, 0));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("No.Exterior:");
        jLabel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanel12.add(jLabel10);

        txt_num.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel12.add(txt_num);

        jPanel3.add(jPanel12);

        jPanel13.setLayout(new java.awt.GridLayout(2, 0, 20, 0));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Usuario:");
        jLabel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanel13.add(jLabel11);

        txt_user.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel13.add(txt_user);

        jPanel3.add(jPanel13);

        jPanel14.setLayout(new java.awt.GridLayout(2, 0, 20, 0));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Contraseña:");
        jLabel12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanel14.add(jLabel12);
        jPanel14.add(txt_password1);

        jPanel3.add(jPanel14);

        jPanel15.setLayout(new java.awt.GridLayout(2, 0, 20, 0));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Confrima Contraseña:");
        jLabel13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanel15.add(jLabel13);
        jPanel15.add(txt_password2);

        jPanel3.add(jPanel15);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, 650));

        jButton_Guardar.setBackground(new java.awt.Color(129, 221, 37));
        jButton_Guardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Guardar.setText("Guardar");
        jButton_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 660, 210, 32));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GuardarActionPerformed

        if (campoVacio()) {

        } else {
            if (Ctrl_Persona.validarCurp(txt_Curp.getText())) {

                if (txt_password1.getText().equals(txt_password2.getText())) {
                    if (txt_password1.getText().isEmpty()) {
                        recuperarDatos();
                        if (Ctrl_Admin.actualizar(adminAux)) {
                            JOptionPane.showMessageDialog(this, "Completado");
                            admin = adminAux;

                        } else {

                        }
                    } else {
                        if (Ctrl_Persona.esContrasenaSegura(txt_password1.getText())) {
                            recuperarDatos();
                            if (Ctrl_Admin.actualizar(admin)) {
                                JOptionPane.showMessageDialog(this, "Completado");

                            } else {

                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "La contraseña debe de tener mas de 5 caracteres.\n"
                                    + "Y contener almenos uno de estos caractres !@#$%&*()_+-=[]|,./?>< ",
                                    "Contraseña no es segura", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Las contraseñas no son iguales");
                }

            } else {
                JOptionPane.showMessageDialog(this, "Formato de CURP no es valido");
            }

        }
    }//GEN-LAST:event_jButton_GuardarActionPerformed
    void ColocarInfo(Administrador admin) {

        txt_user.setText(admin.getUsuario());
        txt_Nombre.setText(admin.getPersona().getNombre());
        txt_apellido1.setText(admin.getPersona().getApellidoP());
        txt_apellido2.setText(admin.getPersona().getApellidoM());
        txt_Curp.setText(admin.getPersona().getCurp());
        txt_CP.setText(admin.getPersona().getDireccion().getCP());
        txt_localidad.setText(admin.getPersona().getDireccion().getLocalidad());
        txt_Calle.setText(admin.getPersona().getDireccion().getCalle());
        txt_num.setText(admin.getPersona().getDireccion().getNumero());
        cBox_estado.setSelectedIndex(admin.getPersona().getDireccion().getEstado() - 1733);
        Jdate_Nacimiento.setDate(admin.getPersona().getNacimiento());
    }

    boolean campoVacio() {
        int i = 0;
        if (txt_password1.getText().isEmpty() && txt_password2.getText().isEmpty()) {

        } else {
            if (txt_password1.getText().isEmpty()) {
                i++;
            }
            if (txt_password2.getText().isEmpty()) {
                i++;
            }
        }
        if (Jdate_Nacimiento.getDate() == null) {
            i++;
        } else {
            if (Ctrl_Persona.esMayor(Jdate_Nacimiento.getDate()) == false) {
                JOptionPane.showMessageDialog(this, "Debes ser mayor de edad para ser administrador", "Solo mayor de 18", JOptionPane.WARNING_MESSAGE);
                return true;
            }
        }
        if (txt_user.getText().isEmpty()) {
            i++;
        }
        if (txt_Nombre.getText().isEmpty()) {
            i++;
        }
        if (txt_apellido1.getText().isEmpty()) {
            i++;
        }
        if (txt_apellido2.getText().isEmpty()) {
            i++;
        }
        if (txt_Curp.getText().isEmpty()) {
            i++;
        }
        if (txt_CP.getText().isEmpty()) {
            i++;
        }
        if (txt_localidad.getText().isEmpty()) {
            i++;
        }
        if (txt_Calle.getText().isEmpty()) {
            i++;
        }
        if (txt_num.getText().isEmpty()) {
            i++;
        }
        if (i == 0) {
            return false;
        } else {
            JOptionPane.showMessageDialog(this, "Completa todos los campos");
            return true;
        }
    }

    public Administrador getAdmin() {
        return admin;
    }

    public void setAdmin(Administrador admin) {
        this.admin = admin;
    }

    void recuperarDatos() {
        Persona p = new Persona();
        Direccion d = new Direccion();

        if (!txt_password1.getText().isEmpty() && !txt_password2.getText().isEmpty()) {
            admin.setPassword(Ctrl_Persona.hashPassword(txt_password1.getText()));

        } else {

        }
        adminAux.setUsuario(txt_user.getText());
        p.setID(adminAux.getPersona().getID());
        p.setNombre(txt_Nombre.getText());
        p.setApellidoP(txt_apellido1.getText());
        p.setApellidoM(txt_apellido2.getText());
        p.setNacimiento(Jdate_Nacimiento.getDate());
        p.setCurp(txt_Curp.getText());
        Date date = new Date(System.currentTimeMillis());
        date.setTime(System.currentTimeMillis());
        System.out.println(date.toString());
        p.setFechaRegistro(date);
        d.setID(adminAux.getPersona().getDireccion().getID());
        d.setEstado(cBox_estado.getSelectedIndex() + 1733);
        System.out.println("Estaod" + cBox_estado.getSelectedIndex());
        System.out.println("Estaod" + cBox_estado.getSelectedItem());
        d.setCP(txt_CP.getText());
        d.setLocalidad(txt_localidad.getText());
        d.setCalle(txt_Calle.getText());
        d.setNumero(txt_num.getText());
        p.setDireccion(d);
        adminAux.setPersona(p);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Jdate_Nacimiento;
    private javax.swing.JComboBox<String> cBox_estado;
    private javax.swing.JButton jButton_Guardar;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField txt_CP;
    private javax.swing.JTextField txt_Calle;
    private javax.swing.JTextField txt_Curp;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_apellido1;
    private javax.swing.JTextField txt_apellido2;
    private javax.swing.JTextField txt_localidad;
    private javax.swing.JTextField txt_num;
    private javax.swing.JPasswordField txt_password1;
    private javax.swing.JPasswordField txt_password2;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables

}
