package vista;

import conexion.Conexion;
import controlador.Ctrl_Admin;
import controlador.Ctrl_Cajero;
import controlador.Ctrl_Cliente;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.plaf.DesktopPaneUI;
import javax.swing.table.DefaultTableModel;
import modelo.Cajero;
import modelo.Cliente;

/**
 *
 * @author ediso
 */
public class InterGestionarCajeros extends javax.swing.JInternalFrame {

    InterEditarCajero editCajero;
    private int idCliente;
    private int indexSelecionado = -1;
    List<Cajero> listaClientes;
    JDesktopPane desk;

    public InterGestionarCajeros(JDesktopPane desk) {
        this.desk = desk;
        initComponents();
        this.setSize(new Dimension(900, 500));
        this.setTitle("Gestionar Cajeros");
        this.repaint();
        DefaultTableModel datos = Ctrl_Cajero.getTablaCajeros();
        this.jTable_Cajeros.setModel(datos);
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        this.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrame1InternalFrameClosing(evt);
            }

            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
    }

    private void jInternalFrame1InternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
        this.dispose();
        if (editCajero != null) {
            editCajero.setVisible(false);
            desk.remove(editCajero);
        }

    }

    void actualizarTabla() {
        DefaultTableModel datos = Ctrl_Cajero.getTablaCajeros();
        this.jTable_Cajeros.setModel(datos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Cajeros = new javax.swing.JTable();
        jButton_actualizar = new javax.swing.JButton();
        jButton_eliminar = new javax.swing.JButton();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrar Cajeros");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_Cajeros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_Cajeros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_CajerosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Cajeros);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 710, 370));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 730, 390));

        jButton_actualizar.setBackground(new java.awt.Color(51, 204, 0));
        jButton_actualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_actualizar.setText("Actualizar");
        jButton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, -1, -1));

        jButton_eliminar.setBackground(new java.awt.Color(255, 51, 51));
        jButton_eliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_eliminar.setText("Eliminar");
        jButton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, 90, -1));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarActionPerformed
        
        
        String opcioes[] = {"Si", "No"};
         if (indexSelecionado >= 0) {
            int op = JOptionPane.showOptionDialog(this, "¿Esta seguro de esta acción?", "¿Eliminar?", JOptionPane.OK_OPTION, 0, null, opcioes, false);
         if (op == 0) {
            //Si
            Cajero cajero = new Cajero();
                String clave = jTable_Cajeros.getModel().getValueAt(indexSelecionado, 3).toString();
                cajero.setClave(clave);
                System.out.println(clave);
                cajero = Ctrl_Cajero.getCajer(cajero);
                Ctrl_Cajero.eliminarPersona(cajero);
                actualizarTabla();

        } else {
            //No
        }
               
            } else {
                JOptionPane.showMessageDialog(this, "Seleccione un cajero");
            }
        // int op= JOptionPane.showConfirmDialog(this,);
        
      


    }//GEN-LAST:event_jButton_eliminarActionPerformed

    private void jButton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarActionPerformed

        if (indexSelecionado >= 0) {
            String clave = jTable_Cajeros.getModel().getValueAt(indexSelecionado, 3).toString();
            InterEditarCajero editCajero = new InterEditarCajero(clave);
            desk.add(editCajero);
            editCajero.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un cajero");
        }


    }//GEN-LAST:event_jButton_actualizarActionPerformed

    private void jTable_CajerosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_CajerosMouseClicked
        indexSelecionado = jTable_Cajeros.getSelectedRow();
        System.out.println(indexSelecionado);

    }//GEN-LAST:event_jTable_CajerosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_actualizar;
    private javax.swing.JButton jButton_eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_Cajeros;
    // End of variables declaration//GEN-END:variables

}
