package vista;

import conexion.Conexion;
import controlador.Ctrl_Lote;
import controlador.Ctrl_Producto;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.Lote;
import modelo.Producto;

/**
 *
 * @author ediso
 */
public class InterNuevoLote extends javax.swing.JInternalFrame {

    public InterNuevoLote() {
        initComponents();
        setTitle("Actualizar Stock de los Productos");
        
    }
    Lote lote;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jDate_Salida = new com.toedter.calendar.JDateChooser();
        txt_Serie = new javax.swing.JTextField();
        jDate_Llegada = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Registro de llegada de lotes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Llegada");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 110, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Fecha de retiro");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 110, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Serie de lote");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, -1));

        jButton1.setBackground(new java.awt.Color(0, 255, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Regitrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 170, 30));
        getContentPane().add(jDate_Salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 170, -1));

        txt_Serie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txt_Serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 170, -1));
        getContentPane().add(jDate_Llegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        registrar();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDate_Llegada;
    private com.toedter.calendar.JDateChooser jDate_Salida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_Serie;
    // End of variables declaration//GEN-END:variables

    public boolean camposVacios() {
        return jDate_Llegada.getDate() == null || jDate_Salida.getDate() == null || txt_Serie.getText().isEmpty();
    }

    void recuperarCampos() {
        // Crear objeto de la clase Lote
        lote = new Lote();

// Obtener fecha de llegada
        Date fechaLlegada = jDate_Llegada.getDate();
        lote.setFechaLLegada(fechaLlegada);

// Obtener fecha de retiro
        Date fechaRetiro = jDate_Salida.getDate();
        lote.setFechaRetiro(fechaRetiro);

// Obtener serie
        String serie = txt_Serie.getText();
        lote.setSerie(serie);
    }

    boolean isDateOK(Date a, Date b) {

// Verificar que la fecha de llegada sea menor a la fecha de retiro
        if (a != null && b != null && a.before(b)) {
            // La fecha de llegada es menor a la fecha de retiro, hacer algo
            return true;
        } else {
            return false;
            // La fecha de llegada no es menor a la fecha de retiro, mostrar un mensaje de error o hacer algo
        }
    }

    void registrar() {
        if (camposVacios()) {
            JOptionPane.showMessageDialog(this, "Rellene todos los campos");
            if (isDateOK(lote.getFechaLLegada(), lote.getFechaRetiro())) {
                if (Ctrl_Lote.existe(lote.getSerie())) {
                    JOptionPane.showMessageDialog(this, "Ya existe un lote identificado por " + lote.getSerie());
                } else {
                    if (Ctrl_Lote.Crear(lote)) {
                        JOptionPane.showMessageDialog(this, "Registro existoso");
                        limpiarCampos();
                    } else {
                        JOptionPane.showMessageDialog(this, "Error");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "La fecha de retiro no puede ser menor a la de entrada");
            }

        }

    }

    private void limpiarCampos() {
        jDate_Llegada.setDate(null);
        jDate_Salida.setDate(null);
        txt_Serie.setText("");
    }
}
